default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5435 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "customer_service_development" } %>

test:
  <<: *default
  database: customer_service_test

production:
  <<: *default
  database: customer_service_production
  username: customer_service
  password: <%= ENV["CUSTOMER_SERVICE_DATABASE_PASSWORD"] %>