production: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      
  workers:
    - queues: critical
      threads: 3
      processes: 2
      polling_interval: 0.1
      
    - queues: default
      threads: 5
      processes: 2
      polling_interval: 1
      
    - queues: low
      threads: 3
      processes: 1
      polling_interval: 5

development:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 1

test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 1